server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ASSINGIT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none